project:
  type: website
  output-dir: docs

website:
  title: "Tiffany Wu"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: art.qmd
        text: Art
    search: true
#  css: custom.css

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: visual

