project:
  type: website
  output-dir: docs

website:
  title: "Tiffany Wu"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: media.qmd
        text: Media
      - href: art.qmd
        text: Art
  search: 
    location: navbar
  #  type: overlay
#  css: custom.css

format:
  html:
  #  theme: 
 #     light: cosmo #minty
  #    dark: slate
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: false
  cache: false
